<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title><?php echo $this->escape($this->title); ?></title>
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl();?>/css/site.css" />
</head>
<body>
<div id="logout">
    <table border=1 bordercolor=none width=1350 height=100 cellpadding=6 cellspacing=0 bgcolor=#e0e0e0>
        <tr>
            <td width="10% align=left">
                <h1>Hello You are logged in!!!</h1>
                <p>
                    <?php
                    if (Zend_Auth::getInstance()->hasIdentity()) {
                        $url = $this->url(array('controller'=>'account', 'action'=>'logout'));
                        echo "<a href=\"{$url}\">Logout</a>";
                    }
                    ?>
                </p>
            </td>
            <td width="100%" align=center>
                <h1 >Content</h1>
            </td>

        </tr>
    </table>


</body>
</html>
