<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/html" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title><?php echo $this->escape($this->title); ?></title>
</head>
<body>
<div id="content">
    <table border=1 bordercolor=none width=1350 height=100 cellpadding=6 cellspacing=0 bgcolor=#e0e0e0>
        <tr>
            <td width="13% align=left">
                <h1>Welcome</h1>
                <form action= "/account/">
                    <p><a href = "<?php echo $this->url(array(
                            'controller' => 'account',
                            'action'  => 'login' ),
                        'default', true); ?>"> Login</a></p>
                    <p><a href = "<?php echo $this->url(array(
                        'controller' => 'account',
                        'action'  => 'useradd' ),
                        'default', true); ?>"> Registration </a></p>
                </form>
            </td>
            <td width="100%" align=rigth>
                <h1><?php echo $this->escape($this->title); ?></h1>
                <?php echo $this->layout()->content; ?>
            </td>
        </tr>
    </table>
</div>
</body>
</html>
