<html>
    <link rel="stylesheet" type="text/css" media="screen" href="/css/content.css"/>

    <table>
        <tr>
            <td id="lf">
                <h1>Welcome</h1>

                <form action= "/account/">
                    <p>
                        <a href = "<?php echo $this->url(array(
                            'controller' => 'account',
                            'action'  => 'login' ),
                            'default', true); ?>"> Login
                        </a>
                    </p>

                    <p>
                        <a href = "<?php echo $this->url(array(
                            'controller' => 'account',
                            'action'  => 'useradd' ),
                            'default', true); ?>"> Registration
                        </a>
                    </p>
                </form>
            </td>

            <td id="rf">
                <h1> Content </h1>

                <?php echo $this->layout()->content; ?>
            </td>
        </tr>
    </table>
</html>