<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/html" xml:lang="en" lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

    <title><?php echo $this->escape($this->title); ?></title>
</head>

<body>

<div id="content">
    <link rel="stylesheet" type="text/css" media="screen" href="/css/content.css"/>

    <table>
        <tr>
            <td id="lf">
                <h1> Hello You are logged in!!! </h1>

                <p>
                <?php
                    if (Zend_Auth::getInstance()->hasIdentity()) {
                        $url = $this->url(array('controller'=>'account', 'action'=>'logout'));
                        echo "<a href=\"{$url}\">Logout</a>";
                    }
                ?>
                </p>
            </td>

            <td id="rf">
                <h1 > Content </h1>
            </td>
        </tr>
    </table>
</div>

</body>

</html>
