<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/html" xml:lang="en" lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

    <title><?php echo $this->escape($this->title); ?></title>
</head>

<body>

<div id="content">
    <link rel="stylesheet" type="text/css" media="screen" href="/css/content.css"/>

    <table>
        <tr>
            <td id="lf">
                <h1> Welcome </h1>

                <form action= "/account/">
                    <p>
                        <a href = "<?php echo $this->url(array(
                            'controller' => 'account',
                            'action'  => 'login' ),
                            'default', true); ?>"> Login
                        </a>
                    </p>

                    <p>
                        <a href = "<?php echo $this->url(array(
                            'controller' => 'account',
                            'action'  => 'useradd' ),
                            'default', true); ?>"> Registration
                        </a>
                    </p>
                </form>
            </td>

            <td id="rf">
                <h1><?php echo $this->escape($this->title); ?></h1>

                <?php echo $this->layout()->content; ?>

                <?php echo $this->form ;?>
            </td>
        </tr>
    </table>
</div>

</body>

</html>

